# Generated by Django 2.1.5 on 2019-11-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pitches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('likedBy', models.TextField()),
                ('dislikedBy', models.TextField()),
                ('tags', models.TextField()),
                ('likeCounter', models.PositiveIntegerField()),
            ],
        ),
    ]
