# Generated by Django 2.1.5 on 2019-11-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitches',
            name='image',
        ),
    ]
